api_platform:
    title: 'API Trippin'
    description: 'api gestion utilisateurs'
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
